# Generated by Django 2.1 on 2020-11-28 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, default=' ', max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('title', models.CharField(blank=True, default=' ', max_length=100)),
                ('content', models.TextField(blank=True, default=' ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_pics')),
                ('title2', models.CharField(blank=True, default=' ', max_length=100)),
                ('content2', models.TextField(blank=True, default=' ')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='blog_pics')),
                ('title3', models.CharField(blank=True, default=' ', max_length=100)),
                ('content3', models.TextField(blank=True, default=' ')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='blog_pics')),
                ('title4', models.CharField(blank=True, default=' ', max_length=100)),
                ('content4', models.TextField(blank=True, default=' ')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='blog_pics')),
                ('title5', models.CharField(blank=True, default=' ', max_length=100)),
                ('content5', models.TextField(blank=True, default=' ')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='blog_pics')),
                ('socials_title', models.CharField(blank=True, default=' ', max_length=100)),
                ('socials_pitch', models.TextField(blank=True, default=' ')),
                ('name_link', models.CharField(blank=True, default=' ', max_length=100)),
                ('link', models.URLField(blank=True, default=' ')),
                ('name_link2', models.CharField(blank=True, default=' ', max_length=100)),
                ('link2', models.URLField(blank=True, default=' ')),
                ('name_link3', models.CharField(blank=True, default=' ', max_length=100)),
                ('link3', models.URLField(blank=True, default=' ')),
                ('tag', multiselectfield.db.fields.MultiSelectField(choices=[('OUR_MISSION', 'Our Mission'), ('FILM_MARKETPLACE', 'Film Marketplace'), ('PUBLIC_SCREENINGS', 'Public Screenings'), ('CONTENT_DELIVERY', 'Content Delivery')], max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=10)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
