# Generated by Django 2.1 on 2020-11-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201125_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default='hi', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content2',
            field=models.TextField(blank=True, default='hi', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content3',
            field=models.TextField(blank=True, default='hi', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content4',
            field=models.TextField(blank=True, default='hi', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, default='www.hi.com', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link2',
            field=models.URLField(blank=True, default='www.hi.com', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
