# Generated by Django 2.1 on 2020-11-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201125_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Type your text here', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content2',
            field=models.TextField(default='Type your text here', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content3',
            field=models.TextField(default='Type your text here', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content4',
            field=models.TextField(default='Type your text here', null=True),
        ),
    ]
