# Generated by Django 3.0.2 on 2020-02-15 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmateurCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie Title', models.CharField(max_length=100)),
                ('Upload a Link to your movie', models.URLField(max_length=128, unique=True)),
                ('Describe the plot of the movie in UNDER 500 chars.', models.TextField(max_length=500)),
                ('Upload a Poster', models.ImageField(blank=True, default='default_movie.jpg', upload_to='movie_pics')),
                ('Upload a Motivational Letter', models.FileField(blank=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadCompetition',
        ),
    ]
