# Generated by Django 3.0.2 on 2020-02-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20200215_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amateurcompetition',
            name='Upload a Motivational Letter',
            field=models.FileField(blank=True, upload_to='competition_letters'),
        ),
        migrations.AlterField(
            model_name='amateurcompetition',
            name='Upload a Poster',
            field=models.ImageField(blank=True, default='default_movie.jpg', upload_to='competition_posters'),
        ),
    ]
