# Generated by Django 3.0.2 on 2020-02-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20200215_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amateurcompetition',
            old_name='Upload a Motivational Letter',
            new_name='Motivational Letter',
        ),
        migrations.RenameField(
            model_name='amateurcompetition',
            old_name='Describe the plot of the movie in UNDER 500 chars.',
            new_name='Plot Description',
        ),
        migrations.RemoveField(
            model_name='amateurcompetition',
            name='Upload a Link to your movie',
        ),
        migrations.RemoveField(
            model_name='amateurcompetition',
            name='Upload a Poster',
        ),
        migrations.AddField(
            model_name='amateurcompetition',
            name='Link to your movie',
            field=models.URLField(default='https://www.artinii.com', max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='amateurcompetition',
            name='Movie Poster',
            field=models.ImageField(default='default_movie.jpg', upload_to='competition_posters'),
        ),
    ]
