# Generated by Django 3.0.2 on 2020-02-16 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_auto_20200215_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='amateurcompetition',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
