# Generated by Django 3.0.2 on 2020-02-17 01:01

import competition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_amateurcompetition_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amateurcompetition',
            name='letter',
            field=models.FileField(blank=True, upload_to='competition_letters', validators=[competition.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='amateurcompetition',
            name='link',
            field=models.URLField(default='https://www.yourmovielink.com', max_length=128, unique=True),
        ),
    ]
