# Generated by Django 3.0.3 on 2020-02-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_auto_20200217_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amateurcompetition',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='amateurcompetition',
            name='link',
            field=models.URLField(help_text='Format: https://www.yourmovielink.com', unique=True),
        ),
        migrations.AlterField(
            model_name='amateurcompetition',
            name='plot',
            field=models.TextField(help_text='500 characters', max_length=500),
        ),
        migrations.AlterField(
            model_name='amateurcompetition',
            name='poster',
            field=models.ImageField(upload_to='competition_posters'),
        ),
    ]
